"""Added event ids

Revision ID: 3b8897961694
Revises: 9b120858c147
Create Date: 2025-08-22 22:24:44.458212

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8897961694'
down_revision: Union[str, Sequence[str], None] = '9b120858c147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbplayer', sa.Column('seen_events', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbplayer', 'seen_events')
    # ### end Alembic commands ###
