"""Separated Units from Items

Revision ID: 6c5201ca1e11
Revises: 3b8897961694
Create Date: 2025-08-27 17:50:50.522923

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5201ca1e11'
down_revision: Union[str, Sequence[str], None] = '3b8897961694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit_rarity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['dbplayer.player_id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.drop_column('item', 'item_rarity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_rarity', sa.VARCHAR(), nullable=True))
    op.drop_table('unit')
    # ### end Alembic commands ###
