"""Separated Item into RPGItem and ValleyItem

Revision ID: 76b3cb8aa710
Revises: 6c5201ca1e11
Create Date: 2025-08-27 18:07:46.047938

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b3cb8aa710'
down_revision: Union[str, Sequence[str], None] = '6c5201ca1e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpgitem',
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['dbplayer.player_id'], ),
    sa.PrimaryKeyConstraint('item_name')
    )
    op.create_table('valleyitem',
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_uses', sa.Integer(), nullable=True),
    sa.Column('cooldown_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['dbplayer.player_id'], ),
    sa.PrimaryKeyConstraint('item_name')
    )
    op.drop_table('item')
    op.alter_column('badge', 'badge_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('badge', 'badge_id')
    op.alter_column('dbplayer', 'equipped_badge',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(None, 'dbplayer', type_='foreignkey')
    op.create_foreign_key(None, 'dbplayer', 'badge', ['equipped_badge'], ['badge_name'])
    op.alter_column('unit', 'unit_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('unit', 'unit_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('unit_id', sa.INTEGER(), nullable=False))
    op.alter_column('unit', 'unit_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'dbplayer', type_='foreignkey')
    op.create_foreign_key(None, 'dbplayer', 'badge', ['equipped_badge'], ['badge_id'])
    op.alter_column('dbplayer', 'equipped_badge',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('badge', sa.Column('badge_id', sa.INTEGER(), nullable=False))
    op.alter_column('badge', 'badge_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('item',
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(), nullable=True),
    sa.Column('item_type', sa.VARCHAR(), nullable=True),
    sa.Column('item_uses', sa.INTEGER(), nullable=True),
    sa.Column('player_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['dbplayer.player_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.drop_table('valleyitem')
    op.drop_table('rpgitem')
    # ### end Alembic commands ###
