"""Modified DBPlayer

Revision ID: 9b120858c147
Revises: 
Create Date: 2025-08-22 20:08:55.630906

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b120858c147'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbplayer', sa.Column('pull_tokens', sa.Integer(), nullable=True))
    op.add_column('dbplayer', sa.Column('total_pulls', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbplayer', 'total_pulls')
    op.drop_column('dbplayer', 'pull_tokens')
    # ### end Alembic commands ###
